name: patinhas s3

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3
    - name: Use Nodejs v16.17.0
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        
        
        # - run: npm ci
    
    - name: Generate project Build
      run: npm run build
    
    - name: Configure AWS CREDENTIALS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Update Bucket
      run: aws s3 cp build/ s3://patinhas-frontend --recursive
